apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
  password: password123

# or can utilize kubectl create secret command to create the secret
# kubectl create secret generic mysql-secret --from-literal=password=password123 --type=kubernetes.io/basic-auth