apiVersion: v1
kind: PersistentVolume
metadata:
  name: alta3-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/g/alta3-pv-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-pv
spec:
  containers:
  - name: nginx-with-pv
    image: nginx:1.18.0
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: nginx-pv-storage
      mountPath: "/mnt"

  volumes:
  - name: nginx-pv-storage
    persistentVolumeClaim:
      claimName: nginx-pvc
